### ISSUE TITLE
CustomFont from URL in iOS 13 

### ISSUE THREAD

**Issue by fbarraganef** [MaddTheSane/SwiftMacTypes#1]
Hi, 
I'm seeing you file from the FontManager and I would ask you maybe you know something related to my curren situation. I'm trying to install in my app a custom font (.ttf file) from a url, but I don't found information related and everything is with the file in the bundle of the application and that's a simple thing, add the file, add to the plist the name and that's it. But when it comes from a external place, is it possible use it in my app? 

I really appreciate your opinion. 

Thanks.

**Comment by MaddTheSane** [comment]
This project is mainly simple wrappers over existing Apple APIs. I can't give any help. Sorry.
